require('./register.cjs');
const {test}=require('node:test'),assert=require('node:assert/strict');
const {snapshot}=require('./growth-pipeline-fixtures.cjs');
const {projectSnapshot}=require('../../server/stock-analysis/growth-radar/pipeline.ts');
const {selectFeatured}=require('../../lib/top3-selection.ts');
const clock=()=>new Date('2026-10-02T00:03:00Z');
function negative(s,index){const d=s.selectionRun.audits[index].report.researchEvidence.majorRisk;d.status='NOT_MET';d.confidence='CONTRADICTED';d.predicateTrace[0].outcome='FAIL';return s;}
test('eligible three plus evidenced formal NOT_MET publishes identical three',()=>{const baseline=projectSnapshot(snapshot(3),clock),s=negative(snapshot(4),3),before=structuredClone(s),r=projectSnapshot(s,clock);assert.equal(r.state,'COMPLETE');assert.equal(r.selectedCount,3);assert.equal(r.candidateCount,3);assert.deepEqual(r.selected,baseline.selected);assert.deepEqual(s,before);});
test('eligible three plus UNVERIFIED still holds publication',()=>{const s=snapshot(4),d=s.selectionRun.audits[3].report.researchEvidence.majorRisk;d.status='UNVERIFIED';d.confidence='UNVERIFIED';d.predicateTrace[0].outcome='UNVERIFIED';const r=projectSnapshot(s,clock);assert.equal(r.selectedCount,0);assert.equal(r.state,'RECHECK_REQUIRED');});
test('formal NOT_MET alone never becomes a candidate',()=>{const r=projectSnapshot(negative(snapshot(1),0),clock);assert.equal(r.selectedCount,0);assert.equal(r.candidateCount,0);assert.deepEqual(r.selected,[]);assert.equal(r.state,'COMPLETE');});
test('existing displayed order is invariant under input reordering and formal exclusion',()=>{const expected=projectSnapshot(snapshot(3),clock).selected.map(c=>c.symbol),s=negative(snapshot(4),3);s.inputs.reverse();s.selectionRun.audits.reverse();s.selectionRun.universe.reverse();assert.deepEqual(projectSnapshot(s,clock).selected.map(c=>c.symbol),expected);});
test('same Selection Engine input has identical output before and after projection',()=>{const s=negative(snapshot(4),3),before=structuredClone(s.selectionRun),expected=selectFeatured(s.selectionRun);projectSnapshot(s,clock);assert.deepEqual(selectFeatured(s.selectionRun),expected);assert.deepEqual(s.selectionRun,before);});
test('unproven or stale NOT_MET cannot clear publication',()=>{for(const change of [d=>{d.evidenceRefs=[];},d=>{d.confidence='UNVERIFIED';},d=>{d.predicateTrace[0].outcome='UNVERIFIED';},d=>{d.predicateTrace[0].factRefs=[];}]){const s=negative(snapshot(4),3);change(s.selectionRun.audits[3].report.researchEvidence.majorRisk);assert.equal(projectSnapshot(s,clock).selectedCount,0);}for(const change of [a=>{a.parserValid=false;},a=>{a.report.researchEvidence.provenance['R13-TEST-DATA'].companyId='E09999';},a=>{a.report.researchEvidence.provenance['R13-TEST-DATA'].documentId='S100OLDX';}]){const s=negative(snapshot(4),3);change(s.selectionRun.audits[3]);assert.equal(projectSnapshot(s,clock).selectedCount,0);}});
test('noncandidate with evidenced formal negative no longer blocks other eligible candidates',()=>{const s=negative(snapshot(4),3);s.inputs[3].sources[0].text='ISOLATED TEST no supported current discovery';assert.equal(projectSnapshot(s,clock).selectedCount,3);s.selectionRun.audits[3].report.researchEvidence.majorRisk.status='UNVERIFIED';assert.equal(projectSnapshot(s,clock).selectedCount,0);});
