
// All attestations in this file are TEST DATA, not generated production evidence.
require("./register.cjs");const {test}=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),crypto=require("node:crypto");
const {audit,run}=require("./top3-fixtures.cjs"),{selectFeatured,candidateBlockers,comparisonDimensions}=require("../../lib/top3-selection.ts");
const {universeFilings}=require("../../server/stock-analysis/top3-universe.ts"),{featuredFromStore}=require("../../server/stock-analysis/featured.ts");
const {onRequest}=require("../../functions/api/stock-analysis/[[path]].ts");
for(const n of [0,1,2,3])test("S7 "+n+" eligible companies without backfill",()=>{const r=run(Array.from({length:n},(_,i)=>audit(String(1111+i))));const copy=structuredClone(r),result=selectFeatured(r);assert.equal(result.entries.length,n);assert.equal(result.state,"COMPLETE");assert.deepEqual(r,copy);});
test("S4 valuation-only STAY qualifies and original status is preserved",()=>{const a=audit("1111",{valuation:"MISSING"}),r=selectFeatured(run([a]));assert.equal(a.report.researchStatus.status,"STAY");assert.equal(r.entries.length,1);assert.deepEqual(r.entries[0].researchStatus,a.report.researchStatus);});
test("S4 STAY with unverified risk, business or counter-thesis is excluded",()=>{for(const condition of ["business","cashFlow","balanceSheet","financials","risk","counterThesis"]){const a=audit();const trace=a.report.researchStatus.ruleTrace.find(t=>t.ruleId==="R1/R2"&&t.reason.includes({business:"事業理解",cashFlow:"CFの持続性",balanceSheet:"財務健全性",financials:"複数年財務",risk:"リスク確認",counterThesis:"この見方"}[condition]));trace.result="PENDING";a.report.researchStatus.status="STAY";assert.equal(selectFeatured(run([a])).entries.length,0);}});
test("GRAY and missing OCF/FCF/Debt never qualify",()=>{for(const key of ["debt","operatingCF","freeCF"]){const a=audit("1111",{[key]:"MISSING"});assert.equal(selectFeatured(run([a])).entries.length,0);}assert.equal(selectFeatured(run([audit("1111",{majorRisk:"UNRESOLVED"})])).entries.length,0);});
test("S1 one family, duplicated CF family or one period cannot qualify",()=>{for(const patch of [o=>o.slice(0,1),o=>o.map(v=>({...v,family:"CASH_FLOW"})),o=>o.map(v=>({...v,periods:v.periods.slice(0,1)}))]){const a=audit();a.observations=patch(a.observations);assert.ok(candidateBlockers(a).includes("MULTI_FAMILY_MULTI_PERIOD_EVIDENCE_MISSING"));}});
test("S5 absent cap and unknown recognition are retained without size proxy",()=>{const r=selectFeatured(run([audit()]));assert.equal(r.entries.length,1);assert.ok(r.entries[0].remainingUnknowns.includes("Recognition UNKNOWN"));assert.ok(!JSON.stringify(r).includes("marketCap"));});
test("S2 PARTIAL supporting unknowns survive without promotion",()=>{const a=audit();a.report.sections.performance[0].confidence="MIXED";const r=selectFeatured(run([a]));assert.equal(r.entries.length,1);assert.equal(r.entries[0].whyNow[0].confidence,"MIXED");assert.ok(r.entries[0].remainingUnknowns.some(s=>s.includes("PARTIAL")));});
test("S6 stale evidence, wrong latest annual, failed parser and partial universe withhold cards",()=>{assert.equal(selectFeatured(run([audit()],{current:false})).state,"RECHECK_REQUIRED");for(const patch of [{latestAnnual:"2025-03-31"},{parserValid:false},{errors:["MAJOR GAP"]}])assert.equal(selectFeatured(run([{...audit(),...patch}])).entries.length,0);assert.equal(selectFeatured(run([audit()],{complete:false})).state,"IN_PROGRESS");});
test("S3/S7 more than three unresolved/tied candidates are not cut by ticker/rates",()=>{const audits=Array.from({length:4},(_,i)=>audit(String(1111+i)));assert.equal(selectFeatured(run(audits)).state,"COMPARISON_REQUIRED");assert.equal(selectFeatured(run([...audits].reverse())).entries.length,0);});
function comparisons(audits,relation){const out=[];for(let i=0;i<audits.length;i++)for(let j=i+1;j<audits.length;j++)out.push({a:audits[i].report.symbol,b:audits[j].report.symbol,relation:relation(i,j),reviewed:true,dimensions:Object.fromEntries(comparisonDimensions.map(d=>[d,{reason:"TEST DATA company-specific "+d,evidenceRefs:["TEST DATA source "+d]}]))});return out;}
test("S3 all eight source-backed comparisons required; no confidence to numeric score",()=>{const audits=Array.from({length:4},(_,i)=>audit(String(1111+i))),r=run(audits);r.comparisons=comparisons(audits,(i,j)=>j===3?"A_STRONGER":"PARALLEL");const selected=selectFeatured(r);assert.equal(selected.entries.length,3);assert.equal(selected.entries.some(e=>e.symbol==="1114.JP"),false);delete r.comparisons[0].dimensions.risk;assert.equal(selectFeatured(r).state,"COMPARISON_REQUIRED");});
test("cyclic comparisons are withheld even with an independent frontier",()=>{const audits=Array.from({length:4},(_,i)=>audit(String(1111+i))),r=run(audits);r.comparisons=comparisons(audits,(i,j)=>j===3?"PARALLEL":i===0&&j===2?"B_STRONGER":"A_STRONGER");assert.equal(selectFeatured(r).state,"COMPARISON_REQUIRED");});
test("same universe/evidence in different presentation order selects same result",()=>{const audits=[audit("1112"),audit("1111")];assert.deepEqual(selectFeatured(run(audits)),selectFeatured(run([...audits].reverse())));});
test("missing trace, unrelated R8 references and duplicate inputs fail closed",()=>{const a=audit();a.report.researchStatus.ruleTrace=[];assert.equal(selectFeatured(run([a])).entries.length,0);const b=audit();b.report.researchStatus.ruleTrace.find(t=>t.ruleId==="R8").evidenceRefs=["UNRELATED TEST DATA"];assert.equal(selectFeatured(run([b])).entries.length,0);assert.equal(selectFeatured(run([audit(),audit()])).state,"RECHECK_REQUIRED");});
test("official metadata distinguishes annual/amendment/half/quarter and respects period end",()=>{const identity=audit().identity;const row=(docID,docTypeCode,periodEnd,submitDateTime,xbrlFlag="1")=>({docID,docTypeCode,periodEnd,submitDateTime,xbrlFlag,edinetCode:identity.edinetCode,secCode:identity.code+"0",withdrawalStatus:"0",disclosureStatus:"0"});const index={version:1,filings:[row("annual","120","2026-03-31","2026-06-01"),row("amended","130","2026-03-31","2026-07-01","0"),row("half","160","2026-09-30","2026-10-01"),row("older","120","2025-03-31","2026-09-01"),row("quarter","140","2026-06-30","2026-08-01")]};const result=universeFilings([identity],index,"2026-10-01")[0];assert.equal(result.latestAnnual,"2026-03-31");assert.equal(result.filingAvailable,false);assert.deepEqual(result.latestDocuments,["amended","half","quarter"]);});
test("featured API ignores manual watchlist and makes no provider requests for unconfigured scan",async()=>{const before=global.fetch;let calls=0;global.fetch=async()=>{calls++;throw new Error("Forbidden");};try{const response=await onRequest({request:new Request("https://tutto.test/api/stock-analysis/featured"),env:{TUTTO_WATCHLIST_SYMBOLS:"7203,285A,7011",STOCK_RATE_LIMITER:{limit:async()=>({success:true})}}});const r=await response.json();assert.equal(response.status,200);assert.equal(r.entries.length,0);assert.equal(r.state,"IN_PROGRESS");assert.equal(r.manifest.coverage.parserVerified,0);assert.equal(calls,0);}finally{global.fetch=before;}});
test("private snapshot date/version changes trigger recheck; no stale automatic continuation",async()=>{const r=run([audit()]);r.manifest.ruleVersion="OLD";const result=await featuredFromStore({get:async()=>r},()=>new Date("2026-10-01T00:00:00Z"));assert.equal(result.state,"RECHECK_REQUIRED");assert.equal(result.entries.length,0);});
test("same-day eligible snapshot without a current official proof is not displayed",async()=>{const r=run([audit()]);const result=await featuredFromStore({get:async()=>r},()=>new Date("2026-10-01T00:00:00Z"));assert.equal(result.state,"RECHECK_REQUIRED");assert.equal(result.entries.length,0);});
test("authorized parser revision and unchanged R1-R10 fingerprints preserve source content",()=>{
 const cp=require("node:child_process"),path=require("node:path");
 const {protectedFiles,parserVersion}=require("../../server/stock-analysis/top3-versions.ts");
 const snapshot=require("./integrity-repair-parser-fingerprints.json");
 const {sha256,verifyProtectedText}=require("./protected-source-fingerprint.cjs");
 assert.deepEqual(snapshot.files.map(row=>row.file),[...protectedFiles]);
 // New authorized parser revision invalidates older snapshots; selection law remains unchanged.
 assert.equal(parserVersion,"edinet/"+sha256(snapshot.files.map(row=>row.file+":"+row.RAW_SHA256).join("\n")));
 const records=snapshot.files.map(record=>{
  const actual=fs.readFileSync(record.file);
  const reference=record.APPROVED_SOURCE_BASE64?Buffer.from(record.APPROVED_SOURCE_BASE64,"base64"):cp.execFileSync("git",["show","HEAD:"+record.file],{cwd:process.cwd(),stdio:["ignore","pipe","pipe"]});
  const result=verifyProtectedText(actual,reference,record);
  assert.equal(result.FINGERPRINT_CHECK,"PASS",record.file+" non-EOL source difference");
  return {file:record.file,expectedRaw:record.RAW_SHA256,expectedCanonical:record.CANONICAL_TEXT_SHA256,...result};
 });
 fs.mkdirSync(".stock-test-output",{recursive:true});
 fs.writeFileSync(path.join(".stock-test-output","protected-source-two-fingerprint-audit.json"),JSON.stringify({contract:snapshot.contract,records},null,2));
});

const {auditCompany}=require("../../server/stock-analysis/discovery.ts"),{emptyPeriod,emptyValuation}=require("../../server/stock-analysis/primary-model.ts");
test("discovery preserves loss-shrinkage values without fabricating negative-denominator growth rates",()=>{
 const id=audit().identity,annual=["2026-03-31","2025-03-31","2024-03-31"].map((end,i)=>{const source={provider:"EDINET",url:"https://api.edinet-fsa.go.jp/api/v2/documents/S100TEST?type=1",title:"EDINET TEST DATA",retrievedAt:"2026-10-01T00:00:00Z",asOf:"2026-06-01",field:"TEST DATA",basis:"annual",period:end,currency:"JPY",unit:"currency",classification:"FACT"};const p=emptyPeriod(end,"annual","JPY",source);for(const k of ["revenue","operatingCF","equity"])p[k].value=100;p.operatingIncome.value=[-1,-2,-3][i];p.capex.value=20;return p;});
 const company={provider:"EDINET",mode:"FREE",identity:{symbol:id.code+".JP",code:id.code,edinetCode:id.edinetCode,name:id.name,country:"JP",currency:"JPY",exchange:"JP"},primarySource:annual[0].revenue.source,description:null,sector:null,industry:null,website:null,cik:null,updatedAt:null,retrievedAt:"2026-10-01T00:00:00Z",annual,quarterly:[],quote:null,valuation:emptyValuation(annual[0].revenue.source),valuationStatus:"LIMITED",earnings:[],filings:[{url:annual[0].revenue.source.url,title:"EDINET TEST DATA",filed:"2026-06-01",period:annual[0].end,amended:false}],issues:[]};
 const a=auditCompany(id,company,"2026-03-31",["S100TEST"]),profit=a.observations.find(o=>o.family==="PROFIT");assert.deepEqual(profit.values,[-1,-2,-3]);assert.deepEqual(profit.growthRates,[null,null]);assert.equal(a.parserValid,true,"parser can operate while Debt is legitimately missing");assert.equal(a.report.researchStatus.status,"GRAY");assert.equal(candidateBlockers(a).includes("DEBT_UNAVAILABLE"),true);
});

test("an inconsistent stored GREEN cannot bypass R4 missing valuation",()=>{const a=audit("1111",{valuation:"MISSING"});a.report.researchStatus.status="GREEN";assert.ok(candidateBlockers(a).includes("GREEN_STATUS_INCONSISTENT"));assert.equal(selectFeatured(run([a])).entries.length,0);});

test("S7 financial fragments cannot be labeled a complete Master report",()=>{const a=audit();delete a.report.sections.scenarios;assert.equal(selectFeatured(run([a])).entries.length,0);assert.ok(candidateBlockers(a).includes("MASTER_REPORT_INCOMPLETE"));});

test("S7 all 25 Master review sections need source-backed review; 12 UI sections are insufficient",()=>{for(const mutation of [a=>a.masterReview=null,a=>a.masterReview.sections.pop(),a=>a.masterReview.sections[0].reviewed=false,a=>a.masterReview.sections[0].evidenceRefs=[],a=>a.masterReview.unresolvedMajorGaps=["MAJOR BUSINESS GAP"],a=>a.masterReview.masterSha="STALE MASTER"]){const a=audit();mutation(a);assert.equal(selectFeatured(run([a])).entries.length,0);assert.ok(candidateBlockers(a).includes("MASTER_25_SECTION_REVIEW_UNVERIFIED"));}});

test("same-day candidates require live official identity and day metadata equality",async()=>{
 const {createHash}=require("node:crypto"),hash=v=>createHash("sha256").update(v).digest("hex"),canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==="object"?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
 const r=run([audit()]),bytes=new TextEncoder().encode("TEST DATA official identity archive"),rows=[{docID:"TEST DATA",status:"TEST DATA unchanged"}];
 r.manifest.freshnessProof={identityArchiveSha:hash(bytes),dayListSha:hash(JSON.stringify(canonical(rows))),day:"2026-10-01"};
 const before=global.fetch;let changed=false,calls=0;global.fetch=async url=>{calls++;const u=new URL(url);assert.ok(["disclosure2dl.edinet-fsa.go.jp","api.edinet-fsa.go.jp"].includes(u.hostname));return u.pathname.endsWith(".zip")?new Response(bytes):new Response(JSON.stringify({metadata:{status:"200"},results:changed?[...rows,{docID:"NEW TEST DATA amendment"}]:rows}));};
 try{let result=await featuredFromStore({get:async()=>r},()=>new Date("2026-10-01T00:00:00Z"),"TEST DATA KEY");assert.equal(result.entries.length,1);changed=true;result=await featuredFromStore({get:async()=>r},()=>new Date("2026-10-01T00:00:00Z"),"TEST DATA KEY");assert.equal(result.entries.length,0);assert.equal(result.state,"RECHECK_REQUIRED");assert.equal(calls,4);}finally{global.fetch=before;}
});
